### ISSUE TITLE
CI: Switch to build-push-action v2 (supports caching)

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-docker-stack#117]
The CI workflows currently take up to 20 mins, because we build the docker image each time anew (~ 15mins). This step could be skipped in the vast majority of cases if we would take advantage of the GitHub actions caching mechanisms which are supported by the [build-push-action](https://github.com/docker/build-push-action/tree/master) v2.

**Comment by csadorf** [comment]
It appears that v2 of the action is still experimental. We should hold off switching until the first proper release.

**Comment by yakutovicha** [comment]
fixed by #127
