### ISSUE TITLE
Inadvertent installation of outdated version of optimade-client

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-docker-stack#152]
We are explicitly installing the `aiidalab-optimade` package here:

https://github.com/aiidalab/aiidalab-docker-stack/blob/08496a441b6b5938eb7b570021e37a851451f919/Dockerfile#L96-L99

This caused a problem in the latest release, because we failed to update this dependency, which means that in the final image we inadvertently installed an outdated version of the `optimade-client` through the `aiidalab-optimade` dependency:

```bash
$ pip list --format=freeze | grep optimade
aiidalab-optimade==1.2.1
optimade==0.12.4
optimade-client==2020.10.29
```

We could of course update this, but since we are no longer relying on `aiidalab-optimade` in `aiidalab-widgets-base`, could we instead remove this completely?

**Comment by csadorf** [comment]
Tagging @yakutovicha and @CasperWA for input.

**Comment by CasperWA** [comment]
> We could of course update this, but since we are no longer relying on `aiidalab-optimade` in `aiidalab-widgets-base`, could we instead remove this completely?

Yes, please.
