### ISSUE TITLE
Opening up for non-root execution of the stack

### ISSUE THREAD

**Issue by espenfl** [aiidalab/aiidalab-docker-stack#172]
Due to the rather extensive set of platforms now not supporting root executions in containers we should consider to opening up for regular users to execute the stack.

The services we require for `aiidalab` can be executed as non-root, but there has been questions regarding the `my_init` script and the framework beneath of the phusion baseimage that we use can support it. We would like to continue using this baseimage due to its process tracking and reaping.

It turns out this is possible, but we loose `cron` and `logrotate` functionality. Do we need this? Paging @yakutovicha @csadorf. I do not think so. Maybe the latter is a problem, but if the logfile becomes so big that it truncates, the systems that requires non-root usually have HA in place, which restarts the container anyway and then you can analyse what is wrong given the current status. We should document this clearly though. See for instance posts: https://github.com/phusion/baseimage-docker/issues/475, especially: https://github.com/phusion/passenger-docker/issues/250#issuecomment-475962752. With `build_args` we can disable `cron`.

**Comment by csadorf** [comment]
I don't think we need logrotate. @yakutovicha ?

**Comment by yakutovicha** [comment]
I am not sure we need logrotate (probably not). However, the reason we build our images on top of the Phusion base image is that it handles zombie tasks. I am not sure this functionality will be working without root permissions.

**Comment by espenfl** [comment]
> I am not sure we need logrotate (probably not). However, the reason we build our images on top of the Phusion base image is that it handles zombie tasks. I am not sure this functionality will be working without root permissions.

What I have seen by looking at `my_init` that should just follow whatever user that executed it and handle the processes from there.

**Comment by danielhollas** [comment]
The new docker stack is executed in non-root mode by default.
