### ISSUE TITLE
Possibility to deploy a clean AiiDAlab

### ISSUE THREAD

**Issue by espenfl** [aiidalab/aiidalab-docker-stack#175]
Right now, e.g. QE is installed by default and that seems rather hard coded. We should open up for an easy way to avoid this and just deploy the basics of AiiDAlab.

In my view this would also not include material science related widgets, only the computer, code etc.

**Comment by csadorf** [comment]
@espenfl Agreed and we are currently working on revising how AiiDAlab is configured and deployed, see https://github.com/aiidalab/aiidalab/pull/174 to follow ongoing work.

**Comment by csadorf** [comment]
This is currently taken care of by @yakutovicha .
