### ISSUE TITLE
should the default route for local deployment go through dockerhub instead?

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-docker-stack#196]
The current default route for local deployment results in users rebuilding the docker image locally, which takes a significant amount of time.

I would recommend to switch the default route to go via the dockerhub image, e.g. 

```
docker pull aiidalab/aiidalab-docker-stack:latest
./run.sh --no-build --image aiidalab/aiidalab-docker-stack:latest 8888 /path/to/dir
``` 

@yakutovicha @csadorf 
I just had a weird experience with dockerhub where my pull seemed extremely slow (some layers were downloading with a few kByte/s). Dockerhub has a [limit of 100 pulls per day for an anonymous user](https://www.docker.com/pricing) (which I've never reached) but to my knowledge there is no rate limiting of downloads.
Could you please check how fast the pull command mentioned above is for you?

**Comment by ltalirz** [comment]
Ok, I repeated the pull command on one of our OpenStack servers and the download of the entire image was completed in <30s (it then took some time for the extraction but that's because the file system there is so slow I guess).

I think it makes sense to use the dockerhub route as the default (note also that we can never guarantee that the docker build is not broken; it can always happen)

**Comment by csadorf** [comment]
@ltalirz I think it is somewhat non-intuitive if any script executed from with the source code repository would not actually run the code in the repository. Are you suggesting that the documented run command should explicitly use the docker hub image, and running it without that option would still build it?

Also, for comparison, in the -demo repository we have a [`control.py`](https://github.com/aiidalab/aiidalab-docker-stack-demo/blob/main/control.py) script that assists with the local deployment. Should we adopt a similar approach here?

**Comment by ltalirz** [comment]
I would always first consider the use case of someone who just wants to be able to run the AiiDAlab locally (i.e. no need to modify the image etc.).

Since Docker image builds take time and are easy to break, for these I think we should suggest to go through Dockerhub.

Of course, a few lines below in the docs we would simply explain which command to run to build the docker image from scratch instead.


> I think it is somewhat non-intuitive if any script executed from with the source code repository would not actually run the code in the repository.

I guess with most docker images one would not have to clone the git repository at all as one can simply run the commands.
It seems you consider this to be too complicated and so provide the `./run.sh`  script.
But of course an alternative would be to just provide the docker command line people need to run.

**Comment by csadorf** [comment]
Ok, so I think we are more or less in agreement. In general, any script that is within the repository should also start source code that is in the repository. Commands that we show in the README that do not require to download/clone the repository could just start the container.

The task is then to develop the minimal command that starts the AiiDAlab instance without any further download. By definition, this command cannot utilize `run.sh`.

**Comment by ltalirz** [comment]
> develop the minimal command that starts the AiiDAlab instance without any further download

So, here is what the `./run.sh` script does:

 1. prepare the arguments needed for `docker run`
    This could be put into the docs explicitly `docker run -d -p 8888:8888 --name aiidalab  -v "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiidalab/aiidalab-docker-stack/vol:/home/aiida" aiidalab/aiidalab-docker-stack:latest`

 2. generate a random jupyterhub access token, forward it to the container, and print the correct URL to connect
    Of course, the instructions could contain a default token, e.g. `-e JUPYTER_TOKEN="my-token"` (I don't see a major security concern here)

 3. Runs the `wait-for-services` script and prints the correct URL once the services are up

One can certainly write all of this down in individual steps - I'm just wondering whether using the `run.sh` script is not more convenient.

**Comment by csadorf** [comment]
One other option would be to simply suggest to download only the script or a similar script and then run it with the hub image. GitHub makes it easy to download individual files so this would be easy to do. I just find it super weird to download the repository and then execute something from the cloud that is independent from the actual source code one just downloaded.

**Comment by ltalirz** [comment]
It is a little weird... at the same time, if you clone the git repo, then switching to building the docker image from scratch is just removing one option from the command.
It also means you don't need to worry about execute permissions on the script... to me it's acceptable.

**Comment by csadorf** [comment]
@ltalirz With the switch to using aiidalab-launch for local deployment, this issue should be resolved.
