### ISSUE TITLE
dependency conflicts with aiida-core docker image

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-docker-stack#199]
The following dependency conflicts were encountered when building on top of the aiida-core:1.6.5 docker image in https://github.com/aiidalab/aiidalab-docker-stack/pull/197

```
#21 15.51 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
#21 15.51 plumpy 0.20.0 requires nest-asyncio~=1.4.0, but you have nest-asyncio 1.5.1 which is incompatible.
#21 15.51 aiida-core 1.6.5 requires pytz~=2019.3, but you have pytz 2021.1 which is incompatible.
```

The first one can likely be avoided by adding `jupyter-client<7` to the `setup.cfg`, see [here](https://github.com/aiidalab/aiidalab-widgets-base/issues/228#issuecomment-919028517)
The pytz dependency [has already been updated in the aiida-core develop branch](https://github.com/aiidateam/aiida-core/blob/d7d1ac650c28ead6a422a8167a0e06123565e1d4/setup.json#L48). This should resolve itself with the next AiiDa release.

**Comment by danielhollas** [comment]
We're now on `aiida-core==2.1.2` so this can be closed.
