### ISSUE TITLE
switch to ubuntu 20.04

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-docker-stack#233]
This is just to mention that for our work Ubuntu 18.04 starts to require workarounds that would not be necessary if we were using ubuntu 20.04.

I.e. this is a vote for Ubuntu 20.04 (of course there are also always reasons against ugrades...)

**Comment by csadorf** [comment]
I believe this is currently blocked by #25 .

**Comment by danielhollas** [comment]
@unkcpz I believe this one can be closed?

**Comment by unkcpz** [comment]
Yep!
