### ISSUE TITLE
delete aiida_1.0_migration branch

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-docker-stack#24]
the [aiidalab_server](https://github.com/marvel-nccr/ansible-role-aiidalab-server) role can install both from dockerhub and from the repo.

In order to keep things simple, I've now copied the `aiida_1.0_migration` into an `aiida-1.0` branch on the repo to match the `aiida-1.0` docker tag (I've also connected the docker tag to it).

@yakutovicha I.e. once you've updated the openstack roles, the  aiida_1.0_migration branch can be deleted.

**Comment by yakutovicha** [comment]
Ok, this is done, the branch is deleted and the corresponding openstack-ansible role is updated.
