### ISSUE TITLE
Avoid overriding packages installed in the system environment.

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-docker-stack#268]
Currently, even if packages are installed in the base environment, they can be superseded by the ones installed in the `.local` folder. I think that better practice would be to forbid installing the core packages (`aiida-core`, `aiidalab`, `aiidalab-widgets-base`).

**Comment by danielhollas** [comment]
@yakutovicha I wonder what is the reason to constrain the AWB version. I cannot now specify the minimum AWB version for my app, and neither am I able to update AWB manually in the  container. One solution would be to have a less restrictive constraint (`>=1.3.4, <2.0` instead of `~=1.3.4`).

**Comment by yakutovicha** [comment]
> @yakutovicha I wonder what is the reason to constrain the AWB version. I cannot now specify the minimum AWB version for my app, and neither am I able to update AWB manually in the container. One solution would be to have a less restrictive constraint (`>=1.3.4, <2.0` instead of `~=1.3.4`).

I thought about this as well. Frankly, after all, I would be in favour of removing AWB from the core dependencies of AiiDAlab. @csadorf what is your opinion on this?

**Comment by csadorf** [comment]
I would also be in favor of that. Considering that the home app does not depend on it either, it seems like that would be a safe choice.
