### ISSUE TITLE
Deploy docker image that supports AiiDA 2.0 on Kubernetes

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-docker-stack#283]
Making sure that the [Docker image stack](https://github.com/aiidalab/aiidalab-docker-stack/tree/stack) can be deployed on

- [x] Minikube for testing
- [x] Azure for production

**Comment by unkcpz** [comment]
Since we have the aiidalab in THEOS and aiida tutorial running as tests, I guess it is safe to close this.
