### ISSUE TITLE
AWB not installable from the App store

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-docker-stack#290]
Because the AWB version is defined as part of the pip constraint file as of #269, it is currently not possible to install AWB from the App store as of the today's release of the 1.4.0 version.

![image](https://user-images.githubusercontent.com/9539441/189991571-176d4806-d1e8-4b62-8c62-c773592afc70.png)

```sh
Defaulting to user installation because normal site-packages is not writeable
Processing /home/aiida/apps/aiidalab-widgets-base
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
ERROR: Cannot install aiidalab-widgets-base 1.4.0 (from /home/aiida/apps/aiidalab-widgets-base) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested aiidalab-widgets-base 1.4.0 (from /home/aiida/apps/aiidalab-widgets-base)
    The user requested (constraint) aiidalab-widgets-base~=1.3.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

I suspect this also breaks the `aiidalab-launch` workflow as it tries to install AWB in the default configuration. Additionally, this prevents Apps to define minimum AWB version as a dependency.

TBH I don't understand why AWB is installed via pip into base image. Wouldn't it make more sense to install it as an AiiDAlab app into /home/aiida/apps during the initial AiiDAlab setup?

CC @yakutovicha @csadorf

**Comment by csadorf** [comment]
> TBH I don't understand why AWB is installed via pip into base image. Wouldn't it make more sense to install it as an AiiDAlab app into /home/aiida/apps during the initial AiiDAlab setup?
> 

Yes, absolutely. I think this is a hold-over from when did not have any mechanism to install "system-wide" dependencies in a different fashion.

The question, is how do we resolve this issue short-term. @yakutovicha Can we create a hot-fix image where we loosen the requirement or remove AWB from the core dependencies entirely?

**Comment by yakutovicha** [comment]
> TBH I don't understand why AWB is installed via pip into base image. Wouldn't it make more sense to install it as an AiiDAlab app into /home/aiida/apps during the initial AiiDAlab setup?

As a side note: we agreed some time ago to remove the AWB from the AiiDAlab registry. It will become a proper python package containing only widgets.
