### ISSUE TITLE
The URL prompt not accessible if docker run with port other than 8888

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-docker-stack#305]
I used the option `-p 8899:8888` to map the port other than `8888`.
The prompt message of the docker run always shows port `8888` in URLs.

**Comment by danielhollas** [comment]
Should it be `-p 8899:8888`?

**Comment by unkcpz** [comment]
Thanks @danielhollas, that's true 🤣. I update the issue, since the first one is still there.

**Comment by danielhollas** [comment]
Hmm, I wonder if the remaining issue can be solved. If you're in the container, you don't know that your port is mapped to another port on host. 

Typical user will use aiidalab-launch which should display the correct host port.

**Comment by unkcpz** [comment]
You are right, I didn't consider the detail. All because too much rely on `aiidalab-launch` for a long time and always has the correct port prompt. I'll let @csadorf comment and if it is not possible (and meaningless) to fix, fell free to close the issue.

**Comment by csadorf** [comment]
Indeed, that is one of the reasons to use aiidalab-launch, because the script inside the container cannot know the external port.
