### ISSUE TITLE
Running services as root in the new aiidalab/full-stack image

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-docker-stack#306]
I have a Docker image built on top of `aiidalab/aiidalab-docker-stack` and I am trying to migrate it to the new `aiidalab/full-stack` image.
One issue that I ran into is moving over my services that run the SLURM scheduler that I am installing inside the image.

Previously, I was using the SYSV system, where I could place a bash script such as the following into the `/etc/service/` directory.

content of`/etc/service/slurmd/run`
```sh
#!/bin/bash
set -em

su -c "slurmctld -D" root
```

It looks like in the new image based on `jupyter/minimal-notebook` this no longer works. On the Jupyter side of things, they are using the `run-one-continuously` to achieve a persistent notebook, and other different scripts are placed in `/usr/local/bin/before-notebook.d/`. Unfortunately, those scripts are executed under user `jovyan`, but SLURM needs root.

So, how do I achieve a persistent service / daemon under root user?

Pinging @csadorf in case you ran into this issue already. Otherwise feel free to ignore and I will have to dig deeper.

btw: This is a useful link for general discussion about various init systems.

https://unix.stackexchange.com/questions/196166/how-to-find-out-if-a-system-uses-sysv-upstart-or-systemd-initsystem

**Comment by csadorf** [comment]
In general you can add start-up scripts as described [here](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#startup-hooks) and you can run the container as root with the [`-e GRANT_SUDO=yes` environment variable](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#permission-specific-configurations).

Alternatively, you could maybe use setuid to execute certain scripts with escalated privileges or re-evaluate whether running them as root is really necessary.

**Comment by danielhollas** [comment]
Hi @csadorf. Thanks so much for the pointers, they were very useful. In the end I made it running, but with one caveat.

In the current setting, it's not possible to run the full-stack container as root, due to the following error:
```
/usr/local/bin/start-notebook.sh: running /usr/local/bin/before-notebook.d/20_start-postgres.sh
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['initdb', '-D', '/home/jovyan/.postgresql']' command failed.  (See above for error)
initdb: error: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
```
Thus, I have made a workaround in `/usr/local/bin/start.sh` to ensure that all the hooks in `/usr/local/bin/before-notebook.d/` are executed as `$NB_USER`. I have placed my slurm services in `/usr/local/bin/start-notebook.d/`, which was empty so far, and that one would be executed by root. This is ugly but it works. The upside is I don't need to grant sudo access to jovyan user, which would be quite unsafe to say the least.

Regardless of the horrible hack, there's no way around the fact that in order to have SLURM under root, I need to execute the container under root. I am afraid this is currently not supported in `aiidalab_launch`, but perhaps it will be at some point, given issue #297.

**Comment by danielhollas** [comment]
Hmm, briefly looking at the `aiidalab-launch` code, it looks like it doesn't actually set a user or a startup command when starting the AiiDAlab container. So perhaps I just need to change USER to root in my Dockerfile and things might work?

I'll close this issue once I can confirm things are working with `aiidalab-launch`.

**Comment by danielhollas** [comment]
Okay, I have tested with the latest aiidalab-launch and things seems to be working (mostly). :tada: 

Some issues I am observing (will submit separate issues once I investigate more)
 - RabbitMQ startup seems flaky, sometimes it doesn't start. When I later enter the container and run the `30_start-rabbitmq.sh` script, it launches without issues.
 - aiidalab-launch successfully launch the container, but it couldn't connect to the notebook, even when it was running and ready. Will need to investigate this more.
 
 I am closing this for now and will submit separate issues.
 
 @csadorf one small questions: What is the purpose of the `/home/jovyan/work/` directory?

**Comment by unkcpz** [comment]
> one small questions: What is the purpose of the /home/jovyan/work/ directory?

Dont know why exactly but it is added here and it says "for backward compatibility" https://github.com/jupyter/docker-stacks/blob/1b04ebe67d28dd6f054cd1e2ea2f9ca78901979f/docker-stacks-foundation/Dockerfile#L82-L84
