### ISSUE TITLE
Add test to check lab stack is started with notebook mode

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-docker-stack#332]
This test is supposed to add along with https://github.com/aiidalab/aiidalab-docker-stack/pull/331 just like what is tested in https://github.com/jupyter/docker-stacks/blob/efa95c2c5b9b095247cd2f5e55bc3b38c85da335/tests/base-notebook/test_start_container.py#L16-L30. 

However, current tests in terms of `base-with-service` and `lab`, the previous one don't have all the lab functionality. 
I'd argue that we test in terms of `full-stack` and `lab`, since `full-stack` is build based on `base-with-service` and therefore cover all the child image. This also makes it possible to test the `lab` and `full-stack` in parallel with full lab functionality test.

What you think? @yakutovicha @danielhollas @superstar54

**Comment by danielhollas** [comment]
@unkcpz I am assuming you mean to change this line?

https://github.com/aiidalab/aiidalab-docker-stack/blob/4556c625571d3a78815d1f44b37107f2b991d897/tests/conftest.py#L19

I don't see a reason why not.
