### ISSUE TITLE
Publish new version of the old docker stack with updated aiidalab and aiidalab-home

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-docker-stack#363]
We should probably create a new support branch for the old docker stack from the last commit before the transition.

**Comment by danielhollas** [comment]
@unkcpz is this one done?

**Comment by unkcpz** [comment]
@yakutovicha mentioned there is some problem that the PostgreSQL version is not correct, and he will take care of it today or tomorrow.

**Comment by yakutovicha** [comment]
It is okay - I will take care of that in another repository. I think the issue can be closed.
