### ISSUE TITLE
should containers work outside JupyterHub

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-docker-stack#37]
@espenfl notes that 
> with the aiida one I get `JUPYTERHUB_API_TOKEN env is required to run jupyterhub-singleuser`. 

Perhaps it would make sense if one could run the aiidalab docker container also outside the JupyterHub?

**Comment by ltalirz** [comment]
From @espenfl
The jupyter containers do this:
```
if [[ ! -z "${JUPYTERHUB_API_TOKEN}" ]]; then
  # launched by JupyterHub, use single-user entrypoint
  exec /usr/local/bin/start-singleuser.sh "$@"
elif [[ ! -z "${JUPYTER_ENABLE_LAB}" ]]; then
  . /usr/local/bin/start.sh $wrapper jupyter lab "$@"
else
  . /usr/local/bin/start.sh $wrapper jupyter notebook "$@"
fi
```

**Comment by yakutovicha** [comment]
That is a good idea. Would you guys be able to make a PR for that? Since the code is here I think it won't take much time for you. I am busy with other stuff this week.

**Comment by espenfl** [comment]
Yes, I will do this.
