### ISSUE TITLE
Can not start the container if the aiida daemon is not properly stopped

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-docker-stack#379]
Step to reproduce, using `full-stack:edge` (which has `aiida-core==2.3.0`, the tag is not exist since we did not release new stack yet.)
1. start the container with aiidalab-launch start -p <profile>
2. stop the container with aiidalab-launch stop -p <profile>
3. start again and it will fail.

The log shows:
```
++ verdi daemon stop
Profile: default
Stopping the daemon... FAILED
Critical: The daemon could not be reached, seemingly because of a stale PID file. Try starting the daemon to remove it and restore the daemon.
```
Exception happened at https://github.com/aiidalab/aiidalab-docker-stack/blob/5a1de2efdf86aab6ab2153eebf9cc728f31d9e68/stack/base/before-notebook.d/40_prepare-aiida.sh#L70-L73

I guess the problem comes from https://github.com/aiidateam/aiida-core/commit/8d963c98fbb3b1224cd69f3860f09360287034b3 where it originally will ignore the stale PID file and create a new one, but now it seems to exit with an exception. @sphuber can you confirm with this guess? 

I think a quick fix can be before running `verdi daemon stop` check and deleting the stale PID files manually.

**Comment by danielhollas** [comment]
> I think a quick fix can be before running verdi daemon stop check and deleting the stale PID files manually.

We should also probably modify `aiidalab-launch` as well to shutdown the daemon gracefully before exiting the container.

**Comment by sphuber** [comment]
Indeed, orphaned PID files can now only be removed by starting the daemon again. So `verdi daemon start` will get rid of the stale PID file after a hard shutdown and start a new daemon.

**Comment by unkcpz** [comment]
> We should also probably modify aiidalab-launch as well to shutdown the daemon gracefully before exiting the container.

Agree. Instead of doing it on aiidalab-launch, I just learned today there is a very interesting tool [s6-overlay](https://github.com/just-containers/s6-overlay) which will handle the service and an ad-hoc services solution for all containers. We can stop the daemon when the container is stopped by using the finalization scripts. I am not sure if this will conflict with `before-notebook.d` or not, I also want to try it to handle the postgresql and rabbitmq more proper.
But for the issue now I think we can have the workaround as #380, what do you think @danielhollas?

**Comment by danielhollas** [comment]
Yes, we need a quick fix soon to unblock other work.

**Comment by unkcpz** [comment]
fixed by https://github.com/aiidalab/aiidalab-docker-stack/pull/382
