### ISSUE TITLE
Re-introduce openbabel back to docker stack?

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-docker-stack#388]
Currently, some of our apps require Openbabel. Unfortunately, the only way to install OpenBabel is through conda. This is sub-optimal because after a container restart - things go away.

It looks like we need to reintroduce the OpenBabel back to the AiiDAlab container. At least, I see no better alternative at the moment.

Thoughts @unkcpz, @danielhollas?

**Comment by unkcpz** [comment]
Where you need this? Which app? I think the good way is to have it in an saparated image like here https://github.com/aiidalab/aiidalab-docker-stack/pull/381

**Comment by danielhollas** [comment]
Before we decide on this, it would be good to know how much would it
increase the image size.

Dne pá 2. 6. 2023 16:25 uživatel Jusong Yu ***@***.***>
napsal:

**Comment by yakutovicha** [comment]
> Before we decide on this, it would be good to know how much would it increase the image size.

I don't know how much the packed image (the one pushed to DockerHub) would increase but a very simple test creating an image from the following Docker file resulted in a 230 MB size increase:

```Docker
FROM aiidalab/full-stack:2023.1013

RUN mamba install --yes \
     openbabel \
     && mamba clean --all -f -y && \
     fix-permissions "${CONDA_DIR}" && \
     fix-permissions "/home/${NB_USER}"
```

**Comment by yakutovicha** [comment]
> Where you need this? Which app? I think the good way is to have it in an saparated image like here #381

The openbabel library is used in [awb](https://github.com/aiidalab/aiidalab-widgets-base/blob/master/aiidalab_widgets_base/structures.py#L738-L760) and [aiidalab-empa-surfaces app](https://github.com/nanotech-empa/aiidalab-empa-surfaces/blob/5907f6546bf70aebf1bd89b715297bad1bea9e0c/surfaces_tools/widgets/cdxml.py#L20) and some more.

What concerns app-specific containers, I think they are too specific. I put my thoughts here: https://github.com/aiidalab/aiidalab-docker-stack/issues/406

**Comment by yakutovicha** [comment]
> Just noting that in the context of AWB, OpenBabel is only optional part of SmilesWidget as a fallback for `rdkit`, and my plan was to remove it since it is not useful in my experience.

That is a good alternative. Shall we do this? I can open a bunch of PRs.

**Comment by danielhollas** [comment]
Go for it.

Dne čt 24. 8. 2023 8:50 uživatel Aliaksandr Yakutovich <
***@***.***> napsal:

**Comment by danielhollas** [comment]
Openbabel was removed from AWB in https://github.com/aiidalab/aiidalab-widgets-base/pull/518 so I think this can be closed. @yakutovicha reopen I you disagree.
