### ISSUE TITLE
Move QE container to aiidalab-qe repo?

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-docker-stack#406]
I would be very much in favour of moving the [QE-related setup](https://github.com/aiidalab/aiidalab-docker-stack/tree/main/stack/qe) to the [aiidalab-qe](https://github.com/aiidalab/aiidalab-qe) repository. I am surprised the decision was made to keep QE-specific stuff in this general repository.

I suggest adding more stacks with different libraries/tools like, queue manager, some materials-science-specific codes (or other-field-specific) etc. However, I would avoid adding the apps themselves.

I think the right place for the QE Docker container is the aiidalab-qe repository. I would encourage other app developers to do the same.

**Comment by unkcpz** [comment]
>  I am surprised the decision was made to keep QE-specific stuff in this general repository.

I solely make this decision. I think it is doable to move it to `aiidalab-qe` which I think is not easy with duplicating too much code at first glimpse. I'll try it and you are correct, if it can be at `aiidalab-qe` repo then it is much better that it has also the advantage of every time a new version is released the new image will be compiled.

**Comment by yakutovicha** [comment]
> I think it is doable to move it to `aiidalab-qe` which I think is not easy with duplicating too much code at first glimpse.

Looking at [the changes](https://github.com/aiidalab/aiidalab-docker-stack/pull/402/files), I would say it is not that big of a problem.

>  I'll try it and you are correct, if it can be at aiidalab-qe repo then it is much better that it has also the advantage of every time a new version is released the new image will be compiled.

Thanks, I will then assign you to the issue. Feel free to ping me if you need any help.

**Comment by unkcpz** [comment]
Done in https://github.com/aiidalab/aiidalab-qe/pull/449
