### ISSUE TITLE
Latest pip `pip check` fails for several packages

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-docker-stack#490]
This is what I see running `pip check` on new builds:

```
async-generator 1.10 is not supported on this platform
certipy 0.1.3 is not supported on this platform
upf-to-json 0.9.2 is not supported on this platform
```

This is a consequence of https://github.com/pypa/pip/issues/12884

~~Short term solution is probably to pin pip to previous version.~~ EDIT: I've fixed the packages on conda-forge instead.

**Comment by danielhollas** [comment]
Opened issues on the corresponding feedstocks

https://github.com/conda-forge/async_generator-feedstock/issues/2
https://github.com/conda-forge/upf_to_json-feedstock/issues/4
https://github.com/conda-forge/certipy-feedstock/issues/1

**Comment by unkcpz** [comment]
thanks @danielhollas 
But where is `async_generator` and `certipy` used? We don't use these dependencies in AiiDAlab I assume?

**Comment by danielhollas** [comment]
They are dependencies of jupyterhub.
