### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-docker-stack#491]
The latest build on main failed with a rather cryptic error in `Set output variables` step which runs `extract-image-names.sh`.

```
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/aiidalab-docker-stack/aiidalab-docker-stack'. Argument list too long
```
https://github.com/aiidalab/aiidalab-docker-stack/actions/runs/10283635135/job/28465139810

It looks like the metadata output from docker/bake-action has gotten too big.

**Comment by danielhollas** [comment]
I submitted an issue upstream: https://github.com/docker/bake-action/issues/239
For now we can pin to previous version of the bake-action.

**Comment by unkcpz** [comment]
Thanks for the fixing, looks all good.
