### ISSUE TITLE
[Dev] Installing `pre-commit` hooks fails due to `PIP_USER=1`

### ISSUE THREAD

**Issue by PNOGillespie** [aiidalab/aiidalab-docker-stack#501]
**Describe the bug**
Installation of `pre-commit` for AiiDALab-QE repository fails when trying to install Hooks, giving the following traceback:
```
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/sirosen/check-jsonschema.
[INFO] Initializing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/jovyan/.cache/pre-commit/repoj5uon3ys/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
stdout: (none)
stderr:
    ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
Check the log at /home/jovyan/.cache/pre-commit/pre-commit.log
```
**To Reproduce**
Following [official instructions](https://aiidalab-qe.readthedocs.io/installation/access_aiidalab/container.html) for installation via Docker container (either `docker run aiidalab/qe:latest` or `aiidalab-launch` with/without aiidalab-qe):

1. Pull latest version of aiidalab-qe docker build
2. Install AiiDALab-QE App with dev tools: `pip install -e .[dev]`
3. Run pre-commit: `pre-commit` (or `pre-commit install-hooks`)

**Version (if known)**
 - App version: 24.10.0a
 - Operating system: Ubuntu 24.04
 - Docker engine version details:
     - Version:           27.2.1
     - API version:       1.47
     - Go version:        go1.22.7
     - Git commit:        9e34c9b
     - Built:             Fri Sep  6 12:08:02 2024
     - OS/Arch:           linux/amd64
     - Context:           default

**Comment by danielhollas** [comment]
There is a (closed) issue about this on pre-commit repo, I commented on it, let's see

https://github.com/pre-commit/pre-commit/issues/1151

**Comment by danielhollas** [comment]
pre-commit will not do anything so we'll need to fix this on our end, but I don't know how yet.

I thought that using an `EXTERNALLY-MANAGED` file in `/opt/conda/lib/python3.9` would do the trick, as per [the specification](https://packaging.python.org/en/latest/specifications/externally-managed-environments/), but unfortunately that disallows user installs as well.

For my own posterity [here's an unhelpful chat with Claude](https://claude.ai/chat/fda1f2d9-1923-45e1-9852-5582309af166)
