### ISSUE TITLE
issues when building locally

### ISSUE THREAD

**Issue by adegomme** [aiidalab/aiidalab-docker-stack#59]
Hi, 
I was trying to build the develop branch locally (to check if adding the bigdft plugin was working). I encountered few issues when launching the container.

- md5 command used in run_aiidalab.sh is not available on my ubuntu system, it seems to be osx specific ? md5sum is the one available, so I had to replace line 15 by 
TOKEN=`date | md5sum | cut -c -32`

- 404 error (from jupyter, so the server runs well) in browser when launching the generated container , it says it can't find http://localhost:8888/apps/apps/home/start.ipynb  . Launching the container from docker hub works, though, so I don't know if it's an issue with local builds only or my changes 

The only thing I change in the recipe is using pip install -e to install aiidalab package from a repository instead of pip, so the diff is basically
```
+COPY opt/aiidalab /opt/aiidalab
+RUN pip install -e /opt/aiidalab
+
 RUN pip install                    \
-    'aiidalab==v20.03.0b2'         \
```

with opt/aiidalab being a clone of https://github.com/aiidalab/aiidalab with just the aiida-bigdft plugin added. 

Edit: and I confirm that undoing all the changes (using the dockerfile from this repo) does not fix things, I still get a 404.

Any idea where this could come from ?

**Comment by yakutovicha** [comment]
Thanks for the report @adegomme. I replaced `md5` with openssl in which seem to be more generic (see #65). I tried to build it on my old ubuntu laptop (both with pulling the image and building it locally) and it all went just fine. 

Can you please pull the repo, switch to the `fix_run_aiidalab_for_ubuntu` branch and try to rerun the `run_aiidalab.sh` script. Also please make sure that the folder you mount is empty (just to have a clean experiment).

Let me know.

**Comment by yakutovicha** [comment]
@adegomme please reopen if the issue persists.

**Comment by adegomme** [comment]
Sorry about the delay, both issues seem indeed fixed now. Thanks a lot !
